### ISSUE TITLE
Support installation for Linux / Windows

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/textbook#2]
We include some scripts to automatically set up the Python environment (see [readme](https://github.com/Qiskit/textbook#setting-up)), but I've only tested it on OSX. To close this issue, we need confirmation that users can run the install script to set up their environment on:

- [x] Linux
   - Tested on Fedora
   - Works with Ubuntu (via GitHub action)
- [ ] Windows

and include any OS-specific instructions .

**Comment by Raghav-Bell** [comment]
@frankharkins Can you please assign this issue to me ?

**Comment by frankharkins** [comment]
Done, thanks!

**Comment by Raghav-Bell** [comment]
Thanks @frankharkins . I have started working on this issue.

**Comment by Algh89110377** [comment]
Hi Frank, I can check the installation on Windows environment if it is not done yet.

**Comment by Raghav-Bell** [comment]
@frankharkins As per requirements.txt, `pyscf==2.0.1` but it breaks installation for windows 64 bit. I have tried various methods to resolve this issue but nothing works see this open issue [Issue with cmake during installation of pyscf #1684](https://github.com/pyscf/pyscf/issues/1684). 
It didn't  come up with OSx as cmake works fine on OSX.

**Comment by frankharkins** [comment]
Good thing we checked! From googling around, it seems using Windows subsystem for Linux (WSL) should work; have you tried that?

@Algh89110377 yes please, the more testers the better 😄

**Comment by Raghav-Bell** [comment]
@frankharkins  Will test on WSL2 and inform you soon.

**Comment by Algh89110377** [comment]
@frankharkins and @Raghav-Bell  I had more success with Git bash. I got more errors with WSL, I am also working on it.

**Comment by Raghav-Bell** [comment]
@frankharkins WSL2 doesn't seem to work as it takes alot time (>2hrs) to install all dependecies and there are dependencies conflict as even warned by @Algh89110377 . I will test on git bash too.



> @frankharkins As per requirements.txt, `pyscf==2.0.1` but it breaks installation for windows 64 bit. I have tried various methods to resolve this issue but nothing works see this open issue [Issue with cmake during installation of pyscf #1684](https://github.com/pyscf/pyscf/issues/1684). It didn't come up with OSx as cmake works fine on OSX.

There is error in `pyscf` installation even with qiskit_nature that's why it was made optional. Can we make it here too as Anaconda envs are easy to work and manage.

**Comment by Algh89110377** [comment]
@frankharkins I made the changes you asked.

**Comment by frankharkins** [comment]
@Raghav-Bell thanks for testing on WSL; which dependencies are conflicting?

**Comment by Raghav-Bell** [comment]
@frankharkins Following dependencies conflicts poped up before complete installation on WSL2 :-```

ERROR: qiskit-ibmq-provider 0.20.2 has requirement numpy<1.24, but you'll have numpy 1.24.3 which is incompatible.
ERROR: qiskit-ibmq-provider 0.20.2 has requirement requests-ntlm<=1.1.0, but you'll have requests-ntlm 1.2.0 which is incompatible.
ERROR: qiskit 0.42.1 has requirement qiskit-aer==0.12.0, but you'll have qiskit-aer 0.12.1 which is incompatible.
ERROR: qiskit 0.42.1 has requirement qiskit-terra==0.23.3, but you'll have qiskit-terra 0.24.1 which is incompatible.
ERROR: ibm-cloud-sdk-core 3.16.7 has requirement urllib3<2.0.0,>=1.26.0, but you'll have urllib3 2.0.3 which is incompatible.
ERROR: ibm-platform-services 0.37.0 has requirement urllib3<2.0.0,>=1.26.0, but you'll have urllib3 2.0.3 which is incompatible.
ERROR: qiskit-ibm-runtime 0.9.3 has requirement numpy<1.24, but you'll have numpy 1.24.3 which is incompatible.
ERROR: google-auth 2.20.0 has requirement urllib3<2.0, but you'll have urllib3 2.0.3 which is incompatible.
```

**Comment by Algh89110377** [comment]
@frankharkins I noticed the issue is still open. May I ask What is the problem with the windows installation? I can work on it.
@Raghav-Bell , may I ask if the WSL-2 installation problem you had is with the package after changes on June 20th? Could you let me know if you checked your python version?

**Comment by Raghav-Bell** [comment]
@Algh89110377 New script again broke on WSL2 with following error:
```
Usage: __main__.py [options]

ERROR: Invalid requirement: --prefer-binary
__main__.py: error: no such option: --prefer-binary
```

**Comment by Algh89110377** [comment]
@Raghav-Bell, thanks, I will start working on it

**Comment by Raghav-Bell** [comment]
> @frankharkins I made the changes you asked.

@Algh89110377 `pyscf` issue is still there, can you please look on this.

**Comment by frankharkins** [comment]
The textbook is being superseded and will not accept any new contributions. Thanks for your help investigating this issue.
