### ISSUE TITLE
Broken Link 

### ISSUE THREAD

**Issue by anamariarojas123** [Qiskit/textbook#48]
Page: https://learn.qiskit.org/summer-school/2022/introduction-linear-algebra-prerequisite-mathematics-circuit-composition#introduction-0-12) 

On that page towards the bottom, the "Suggested reading Learn Quantum Computation Using Qiskit: 8.1 Linear Algebra"  link is broken.

**Comment by Raghav-Bell** [comment]
This issue is similiar to [platypus issue #2118](https://github.com/Qiskit/platypus/issues/2118)

**Comment by frankharkins** [comment]
Fixed by @Raghav-Bell, thanks both!
