### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/textbook#5]
#### New contributors
The textbook is a good starting point for first time GitHub contributors. We should make sure the contributing docs are clear & accurate.
- [ ] Test on OSX users
- [ ] Test on Windows users

### Textbook-specific docs
We should document things that are non-standard, or might not be obvious to experienced users working on the textbook.
- [ ] Add info on custom syntax for widgets

**Comment by Raghav-Bell** [comment]
Is this issue still open? can i contribute here?

**Comment by Algh89110377** [comment]
Hi Frank, if this issue is open, can I test the contributors' instructions on MacOs and Windows and see if it works without a hiccup?

**Comment by frankharkins** [comment]
Closing as the textbook has been superseded and will accept no more contributions.
