### ISSUE TITLE
Explain how to cite the textbook

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/textbook#6]
We should make it clear how to cite the textbook. We did have a bibtex file a while ago, but I think a link to this repo is more appropriate now.

**Comment by Raghav-Bell** [comment]
I will like to work on this if it is not resolved yet.

**Comment by frankharkins** [comment]
@Raghav-Bell thanks. I think a short note in the README is enough to close this issue. I think listing the authors as "various authors" and linking to this repo is fine.

**Comment by Raghav-Bell** [comment]
Thanks @frankharkins for assigning this issue to me. While surfing for citation of github project, i got to know about [CITATION.cff](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files ) file. I can add that too, if required.
