### ISSUE TITLE
The AerSimulator is imported from incorrect package.

### ISSUE THREAD

**Issue by nikolabintev** [Qiskit/textbook#69]
**Where is the problem?**
https://learn.qiskit.org/course/introduction/the-atoms-of-computation

**Describe the problem**
In the "Your first quantum circuit" section the package that is used to import the `AerSimulator` is incorrect.
**Expected behavior**
Instead of importing the `AerSimulator` from `qiskit.providers.aer` it should be imported from `qiskit_aer`. At least this is what works locally.
```[tasklist]
### Tasks
- [ ] https://github.com/Qiskit/textbook/pull/70
```

**Comment by SahilDahat** [comment]
I'm interested in contributing to this matter and would appreciate guidance on locating the resource at `https://learn.qiskit.org/course/introduction/the-atoms-of-computation.`

**Comment by nikolabintev** [comment]
Hi @SahilDahat I just opened a PR. Could you please review: https://github.com/Qiskit/textbook/pull/70

**Comment by nikolabintev** [comment]
I am closing the issue as the pull request has been merged.
