### ISSUE TITLE
Last circuit on Classical Computation on a Quantum Computer not displaying correctly

### ISSUE THREAD

**Issue by zimmermant** [Qiskit/textbook#74]
**Where is the problem?**
[Classical Computing on a Quantum Computer - Qiskit Textbook
](https://learn.qiskit.org/course/ch-gates/classical-computation-on-a-quantum-computer) very near the bottom of the page.
**Describe the problem**
The output from the last interactive box produces an image different than the original image.  In other words, running `(Vf.inverse().compose(copy).compose(Vf)).draw()` changes the circuit shown immediately below it.  Instead it shows a circuit with only three qubits.

**Expected behavior**
The code should display a circuit with four qubits.

**Screenshots**

This is what you should see (and do immediately after reloading the page):

<img width="540" alt="Screenshot 2023-08-16 at 2 21 52 PM" src="https://github.com/Qiskit/textbook/assets/7947401/a117750c-758f-49e6-86d5-7a6804635ad1">

This is the result you get from running all the code on the page:
<img width="540" alt="Screenshot 2023-08-16 at 2 22 48 PM" src="https://github.com/Qiskit/textbook/assets/7947401/aeea6203-34f3-4b38-9a12-98551b215672">

**Comment by frankharkins** [comment]
Thanks for making this issue. The textbook is being superseded so this will not be fixed.
