### ISSUE TITLE
Tex error on HHL Algorithm page

### ISSUE THREAD

**Issue by rejeesh09** [Qiskit/textbook#81]
**Where is the problem?**
https://learn.qiskit.org/course/ch-applications/solving-linear-systems-of-equations-using-hhl-and-its-qiskit-implementation 

**Describe the problem**
On the solving linear systems of equations using HHL algorithm and its Qiskit implementation page in section 2.2/2.B the second and fifth points are not legible due to incorrect Tex formatting.

**Expected behavior**
Proper math format.

**Screenshots**
![qiskit_hhl_page_math_format](https://github.com/Qiskit/textbook/assets/22218031/068024bc-f0a3-4d44-a6c1-a01635c63edf)

**Comment by Raghav-Bell** [comment]
Please let me take this issue.
