### ISSUE TITLE
Textbook setup doesn't work on Windows

### ISSUE THREAD

**Issue by uarmbruester** [Qiskit/textbook#87]
**Describe the bug**
When executing the command "install.sh" I get the error:
ERROR: The tar file (C:\Users\A400919\AppData\Local\Temp\pip-unpack-8e74pa24\pyscf-2.0.1.tar.gz) has a file (C:\Users\A400919\AppData\Local\Temp\pip-install-1y5k_ggc\pyscf_a7e51574f1e84b7e821cb21216ad8b29\pyscf/agf2/aux.py) trying to install outside target directory (C:\Users\A400919\AppData\Local\Temp\pip-install-1y5k_ggc\pyscf_a7e51574f1e84b7e821cb21216ad8b29)
![Qiskit install](https://github.com/Qiskit/textbook/assets/147490779/42edf163-e515-4b7e-8b11-62266a0bf85c)

**To Reproduce**
1. Go to Github/textbook
2. Run script 'install.sh
3. See error above

**Expected behavior**
The script doesn't terminate with success, throws an error instead

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Program versions: Python 3.9.1

**Additional context**
According to my first assessment this is due to the file aux.py which is an invalid filename on Windows

**Comment by frankharkins** [comment]
Thanks for making this issue, I'm closing this as the textbook is no longer accepting contributions, so environment setup is not necessary any more.
